service: serverless-cifar
 
provider:
  name: aws #cloud provider
  region: ap-south-1
  memorySize: 3000 #memory usage
  timeout: 300 
 
functions:
  cifar:
    image: 467412868237.dkr.ecr.ap-south-1.amazonaws.com/cifar-serverless:latest
    events:
      - http:
          path: inference 
          method: post 
          cors: true